services:
  wordpress:
    build:
      context: ./wordpress
      args:
        - SERVER_HOST
        - SERVER_PORT
        - SERVER_USER
        - SERVER_PATH
      secrets:
        - ssh_key
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress-data:/var/www/html/:rw
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql:rw
      - db-initial-data:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wpuser
      PMA_PASSWORD: password

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db-data

  db-initial-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db-initial-data

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress-data

secrets:
  ssh_key:
    file: ${SSH_KEY_PATH}
